# Generated by Django 4.2.4 on 2023-10-15 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_sold_to_alter_bid_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
